version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
     
      AUTH0_ISSUER_BASE_URL: YOUR_AUTH0_URI
      AUTH0_AUDIENCE: milanauthapi
      # ⚠️ Added this to match your middleware's expectations
      AUTH0_TOKEN_ALG: RS256
